food = {
    "What is food ?" : "any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth",
    "What are the types of food ?" : "Veg and Non-Veg",
    "Which food is good for health ?" : "Fruits and Vegitables",
    "Which food has more calory ?" : "Red meats,pork and chicken",
    "Which food has more protein ?" : "Eggs",
    "Which nutritions does the egg have ?" : "High-quality protein,Saturated fat,vitamins and carotinoids",
    "Which food has more Carbohydrates ?" : "Rice and food which are made with rice",
    "Taking Rice thrice in a day is good for health ?" : "No,It's not good for health",
    "What is the good food habit ?" : "Idly,vada,dosa in morning and in the afternoon take some rice food along with vegetables and in the night take wheat food!",
    "Which Vegetable has Vitamin A ?" : "Sweat potato and carrot",
    "What is use of Vitamin A ?" : "It is essential for normal vision,immune system and reproduction",
    "Which fruit has vitamin A ?" : "Tomato,papaya,mango and watermelon",
    "What is the source of vitamin B ?" : "milk,cheese,eggs and dark-green vegetable",
    "What is the use of vitamin B ?" : "It keeps body's nerve and blood cells healthy",
    "How many types does the vitamin B have ?" : "There are 8 types",
    "What are the types of vitamin B ?" : "B1,B2,B3,B5,B6,B7,B9,B12",
    "What problem will arise due to vitamin C deficiency ?" : "It may cause scurvy",
    "What will be the remedy for scurvy ?" : "Eat vitamin C enriched foods like citrus fruits like gooseberry,guava and mango,papaya,pine apple",
    "What are the sources of vitamin D ?" : "Fishes,eggs,milk and mushrooms",
    "what are food to be taken for rickets ?" : "Fishes,eggs,milk and mushrooms",
    "what is the role of vitamin D ?" : "It helps to regulate the amount of calcium and phosphate.These nutrition keeps our bone and muscles healthy.",
    "list out some vitamin E enriched foods" : "sunflower seeds,spinach and vegetable oils",
    "What is the result of vitamin E deficiency?" : "It causes chronic pancreatitis, cholestasis, cystic fibrosis",
    "What is the source of vitamin K ?" : "Green leafy vegetables, such as kale, spinach, turnip greens, collards, Swiss chard, mustard greens, parsley, romaine, and green leaf lettuce",
    "what is the effect of vitamin K deficiency ?" : "Vitamin K deficiency can contribute to significant bleeding, poor bone development, osteoporosis, and increased cardiovascular disease.",
    "what is the role of vitamin K ?" : "Vitamin K refers to a group of fat-soluble compounds. There are several vitamin K-dependent proteins involved in coagulation, bone development, and cardiovascular health.",
    "What kind of nutrition does the fish have ?" : "Fish is a low-fat high quality protein. Fish is filled with omega-3 fatty acids and vitamins such as D and B2 (riboflavin). Fish is rich in calcium and phosphorus and a great source of minerals, such as iron, zinc, iodine, magnesium, and potassium.",
    "which oil is good for health ?" : "Canola,Corn,Olive,Peanut,Safflower,Soybean,Sunflower",
    "What is food poisoning ?" : "Illness caused by food contaminated with bacteria, viruses, parasites or toxins.",
    "What is the cause of food poisoning ?" : "Infectious organisms or their toxins are the most common causes of food poisoning.",
    "Tips for avoiding food poisoning" : "Wash your hands,Wash worktops,Wash dishcloths,Use separate chopping boards,Keep raw meat separate,Store raw meat on the bottom shelf,Cook food thoroughly,Keep your fridge below 5C.",
    "Which food helps for hair growth ?" : "Eggs,spinach and sweat potato",
    "What is the balanced diet ?" : "A balanced diet is a diet that contains differing kinds of foods in certain quantities and proportions so that the requirement for calories, proteins, minerals, vitamins and alternative nutrients is adequate and a small provision is reserved for additional nutrients to endure the short length of leanness.",
    "Which food causes obesity ?" : "eating junk food frequently - fast food meals, cakes and pastries, sweets, processed meats and sugary drinks are loaded with kilojules.",
    "How can we avoid obesity" : "Exercise regularly. You need to get 150 to 300 minutes of moderate-intensity activity a week to prevent weight gain,Follow a healthy-eating plan.",
    "What are the famous food in Tamil Nadu ?" : "Idly,vada,dosa,pongal,biriyani",
    "What are nutrients does the greens have ?" : "Dark green veggies are a rich source of minerals including iron, calcium, potassium, and magnesium. They also provide important vitamins, including vitamins K, C, E, and many of the B vitamins",
    "Can we eat mushrooms ?" : "Yes,but we have to select the eatable mushrooms otherwise it's leads to some health issues",
    "List out the restaurants in Tamil Nadu  ?" : "City cafe,Dharmalingam,Dindukkal Thalappakatti hotel,Hotel Himalayas",
    "what is food" : "any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth",
    "what is a food" : "any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth"
}