gaming = {
    "Which is the trending game in mobile now" : "Among us is a game which is recently trending around the world.",
    "Who is the developer of among us" : "Among us was developped by a company called innersloth.",
    "What is the maximum number of players in among us" : "Among us can be played by maximum of 10 players at a time.",
    "What is the original name of among us" : "The original name of among us is space mafia.",
    "How many maps are there in among us?" : "There are 3 maps in among us.They are SKELD,MIRAHQ & POLUS.",
    "Is among us available for windows" : "Yes among is availble for windows but it costs 5 USD.",
    "List few games of less size and more intersting to play ." : "Among us , Minimilitia , chess,etc.",
    "Can we speak during among us game" : "No, audio feature while playing the game is not yet avilable & may come in future.",
    "What does PUBG mean" : "PUBG stands for Player Unknown's Battle Ground.",
    "Why is PUBG mobile banned in INDIA" : "PUBG the most played online multiplayer game is banned in INDIA due to security reasons i.e the players information are not protected.",
    "Is PUBG availabe for PC" : "Yes, PUBG is available for PC but it's not free.",
    "Name some mostly downloaded games in playstore ." : "Garena Free Fire, Subways Surfers, Sniper 3D Assassin.",
    "What is the size of among us" : "According to the game's description on the Google Play Store, the download size for Among Us is roughly 70 MB.",
    "What is the size of PUBG mobile" : "According to the game's description on the Google Play Store, the download size for PUBG is roughly 1.8 GB.",
    "What are all the maps in PUBG mobile" : "The maps are erangel,miramar,shanhok and vikendi.",
    "When was PUBG mobile banned in INDIA" : "PUBG Mobile was banned in India on 4 September.",
    "What is meant by COC" : "COC stands for clash of clans an online multiplayer game.",
    "How to download a game from playstore" : "Open playstore in your mobile.Search for the game you need and click it.Now click and the game will be installed in your mobile phone.",
    "Who developed PUBG mobile" : "PUBG mobile was developed by PUBG CORPORATION and KRAFTON UNION.",
    "Who developed subway surfers" : "Subway Surfers is an endless runner mobile game co-developed by Kiloo and SYBO Games.",
    "What is FORTNITE" : "Fortnite is an online video game developed by Epic Games and released in 2017.",
    "Tell about minecraft" : "Minecraft is an open-ended, exploration- and creation-focused environment. Players can create items and buildings from scratch using materials they harvest from the world around them.",
    "What is the size of FORTNITE" : "The overall consensus by players is that the average size of Fortnite is now 26 GB on PC.",
    "What is the size of minecraft" : "In terms of game file size, you will need at least 1 GB of free disk space available for Minecraft PC.",
    "What is the size of asphalt 9" : "The Asphalt 9 download size is around 1.85GB.",
    "What is the download size of subway surfers" : "The Subway surfers download size is around 100 MB.",
    "Which is the best game in mobile" : "Asphalt 9: Legends.",
    "Which is the best game in PC" : "Mine craft , fortnite & PUBG.",
    "Which game has highest downloads in playstore" : "Stack Ball was the most downloaded game on Google Play worldwide.",
    "Name some streaming platforms for games." : "Twitch , youtube , Smashcast,etc",
    "Tell about minimilitia ." : "Mini Militia - Doodle Army 2 is all about intense multiplayer combat! Battle with up to 6 players online in this fun 2D cartoon-themed cross.",
    "What is the size of minimilitia" : "Minimilitia's download size is about 85 MB.",
    "How many maps are ther in minimilitia" : "There are about 15 maps in Minimilitia.",
    "What does COD stand for" : "COD stands for Call of duty.",
    "Who is the developer of human fall flat" : "Human fall flat is developed by No break games and codeglue.",
    "What is DBD" : "DBD stands for dead by daylight .",
    "Name some recently trending PC games ." : "Fallguys knockout , human fall flat , among us,etc",
    "Tell about human fall flat ." : "In Human Fall Flat you play as a wobbly human who keeps dreaming about surreal places filled with puzzles where he's yet to find the exit.",
    "Name some of the puzzle games for mobile ." : "Sky: Children of the Light,Total Party Kill,urn It On! Free,etc",
    "Who is the developer of candy crush" : "Candy Crush Saga is a free-to-play match-three puzzle video game released by company called King.",
    "What is twitch" : "Twitch is the world's leading live streaming platform for gamers.",
    "Name some car simulation games" : "Dr driving , Dr parking , Extreme car simulation",
    "Tell about fall guys game ." : "Fall Guys: Ultimate Knockout (or simply Fall Guys) is a platformer battle royale game developed by Mediatonic and published by Devolver Digital.",
    "Who is the developer of fall guys" : "Fall guys was developed by Mediatonic",
    "Who is the developer of GTA vice city" : "Rockstar games",
    "What is a game" : "a form of play or sport with rules; a time when you play it"
}