science = {
    "Who invented periodic table" : "Dmitri Mendeleev",
    "Which is the most abundant gas in the earth's atmosphere" : "Nitrogen",
    "Which toxic element present in automobile exhausts" : "Lead",
    "Which gases cause acid rain" : "Sulphur dioxide, Nitrogen oxides",
    "Which metal is used in the making of microchips" : "Silicon",
    "What is sodium chloride" : "Table Salt",
    "What is the element present on lead pencils" : "Carbon(Graphite)",
    "Which gas is found in soda water" : "Carbondioxide",
    "What is marsh gas" : "Methane",
    "Which is the purest form of carbon" : "Graphite",
    "Which is called white poison" : "Sugar",
    "Which is the simplest sugar" : "Glucose",
    "Which element is a liquid at ordinary temperature" : "Mercury",
    "Which Vitamin is also known as retinol" : "Vitamin A",
    "Which Vitamin is called niacin" : "Vitamin B3",
    "What is Calciferol" : "Vitamin D",
    "What is called thiamine" : "Vitamin B1",
    "Which heavy metal causes Itai Itai disease" : "Cadmium",
    "What is the popular programming language used today" : "Python. It is an interpreted, high-level and general-purpose programming language. Created by Guido van Rossum and first released in 1991",
    "What is a chatbot" : "A chatbot is a software application used to conduct an on-line chat conversation via text or text-to-speech, in lieu of providing direct contact with a live human agent",
    "What is Natural Language Processing (NLP)" : "Natural language processing (NLP) is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data",
    "What is a compiler" : "A compiler is a program that converts instructions into a machine-code or lower-level form so that they can be read and executed by a computer.",
    "what is the first search engine on internet" : "Archie. It is a tool for indexing FTP archives, allowing people to find specific files. It is considered to be the first Internet search engine. The original implementation was written in 1990 by Alan Emtage, then a postgraduate student at McGill University in Montreal.",
    "Number of bits used ny ipv6 address" : "IPv6 address uses 128 bits",
    "what is the first computer virus known as" : "Creeper Virus",
    "Which programming language is used exclusively for artificial intelligence" : "Prolog. It is a logic programming language associated with artificial intelligence and computational linguistics.",
    "What is a computer" : "A computer is an electronic machine that can store, find and arrange information, calculate amounts and control other machines.",
    "What is a CPU" : "A central processing unit (CPU), also called a central processor, main processor or just processor, is the electronic circuitry within a computer that executes instructions that make up a computer program. The CPU performs basic arithmetic, logic, controlling, and input/output (I/O) operations specified by the instructions in the program.",
    "What is a keyboard" : "A computer keyboard is a typewriter-style device which uses an arrangement of buttons or keys to act as mechanical levers or electronic switches. Replacing early punched cards and paper tape technology, interaction via teleprinter-style keyboards have been the main input method for computers since the 1970s, supplemented by the computer mouse since the 1980s.",
    "What is a computer mouse" : "A computer mouse is a hand-held pointing device that detects two-dimensional motion relative to a surface. This motion is typically translated into the motion of a pointer on a display, which allows a smooth control of the graphical user interface of a computer.",
    "What is a program" : "A computer program is a collection of instructions that can be executed by a computer to perform a specific task.",
    "What is a robot" : "A robot is a machine, especially one programmable by a computer capable of carrying out a complex series of actions automatically. Robots can be guided by an external control device or the control may be embedded within.",
    "what are the uses of robots" : "Robots are widely used in manufacturing, assembly and packing, transport, earth and space exploration, surgery, weaponry, laboratory research, and mass production of consumer and industrial goods.",
    "What is robotics" : "Robotics is an interdisciplinary research area at the interface of computer science and engineering. Robotics involves design, construction, operation, and use of robots. The goal of robotics is to design intelligent machines that can help and assist humans in their day-to-day lives and keep everyone safe.",
    "List todays's Trending technologies" : "Artificial Intelligence, Machine Learning, Robotic Process Automation(RPA), Edge Computing, Virtual Reality and Augmented Reality, Cybersecurity, Blockchain, Internet of Things(IoT)",
    "What is Artificial Intelligence" : "Artificial intelligence (AI) refers to the simulation of human intelligence in machines that are programmed to think like humans and mimic their actions. The term may also be applied to any machine that exhibits traits associated with a human mind such as learning and problem-solving.",
    "What is Machine Learning" : "Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. Machine learning focuses on the development of computer programs that can access data and use it learn for themselves.",
    "What is Robotic Process Automation (RPA)" : "Robotic Process Automation is the technology that allows anyone today to configure computer software, or a robot to emulate and integrate the actions of a human interacting within digital systems to execute a business process. RPA robots utilize the user interface to capture data and manipulate applications just like humans do. They interpret, trigger responses and communicate with other systems in order to perform on a vast variety of repetitive tasks.",
    "What is Edge Computing" : "Edge computing is a distributed computing paradigm that brings computation and data storage closer to the location where it is needed, to improve response times and save bandwidth.",
    "What is Virtual Reality" : "Virtual Reality (VR) is the use of computer technology to create a simulated environment. Unlike traditional user interfaces, VR places the user inside an experience. Instead of viewing a screen in front of them, users are immersed and able to interact with 3D worlds.",
    "What is Augmented Reality" : "Augmented reality (AR) is an interactive experience of a real-world environment where the objects that reside in the real world are enhanced by computer-generated perceptual information, sometimes across multiple sensory modalities, including visual, auditory, haptic, somatosensory and olfactory.",
    "Difference between augmented reality and augmented reality" : "Augmented reality (AR) adds digital elements to a live view often by using the camera on a smartphone... Virtual reality (VR) implies a complete immersion experience that shuts out the physical world.",
    "What is Cybersecurity" : "Cybersecurity is the protection of internet-connected systems such as hardware, software and data from cyber-threats. The practice is used by individuals and enterprises to protect against unauthorized access to data centers and other computerized systems.",
    "What is Blockchain Technology" : "Blockchain is a system of recording information in a way that makes it difficult or impossible to change, hack, or cheat the system. A blockchain is essentially a digital ledger of transactions that is duplicated and distributed across the entire network of computer systems on the blockchain.",
    "What is Internet of things (IoT)" : "The Internet of things (IoT) describes the network of physical objects-'things'-that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the Internet.",
    "What is Data Science" : "Data science is an inter-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from many structural and unstructured data. Data science is related to data mining, machine learning and big data.",
    "What is Quantum Computing" : "Quantum computing is the use of quantum phenomena such as superposition and entanglement to perform computation. Computers that perform quantum computations are known as quantum computers.",
    "What is Information Technology" : "Information technology is the use of computers to store, retrieve, transmit and manipulate data or information. IT is typically used within the context of business operations as opposed to personal or entertainment technologies. IT is considered to be a subset of information and communications technology.",
    "What is Cloud Computing" : "Cloud computing is the on-demand availability of computer system resources, especially data storage and computing power, without direct active management by the user. The term is generally used to describe data centers available to many users over the Internet.",
    "What is Nano Technology" : "Nanotechnology is the use of matter on an atomic, molecular, and supramolecular scale for industrial purposes. The earliest, widespread description of nanotechnology referred to the particular technological goal of precisely manipulating atoms and molecules for fabrication of macroscale products, also now referred to as molecular nanotechnology.",
    "What is Material Science" : "The interdisciplinary field of materials science, also commonly termed materials science and engineering, is the design and discovery of new materials, particularly solids.",
    "Uses of chatbot" : "Chatbots are being made to ease the pain that the industries are facing today. The purpose of chat bots is to support and scale business teams in their relations with customers. It could live in any major chat applications like Facebook Messenger, Slack, Telegram, Text Messages, etc.",
    "What is Gravity" : "Gravity is a physical connection between space and matter that is precisely described by Einstein's 1915 geometric theory of gravity known as General Relativity.",
    "Who is the father of Physics" : "Galileo Galilei. He has also been called the 'father of modern observational astronomy', the 'father of modern physics', the 'father of science', and 'the father of modern science'.",
    "Who is the father of Chemistry" : "Antoine Lavoisier",
    "Who is the father of Mathematics" : "Archimedes (287 BC-212 BC) is known as Father of Mathematics.",
    "Who is the father of Zoology" : "Aristotle (384 - 322 B.C.)",
    "Who is the father of Botany" : "Theophrastus (371 - 287 BC)",
    "Who is the father of Computer" : "Charles Babbage",
    "What is a software" : "Computer software, or simply software, is a collection of data or computer instructions that tell the computer how to work. This is in contrast to physical hardware, from which the system is built and actually performs the work.",
    "What is a hardware" : "Computer hardware includes the physical parts of a computer, such as the case, central processing unit, monitor, mouse, keyboard, computer data storage, graphics card, sound card, speakers and motherboard. By contrast, software is the set of instructions that can be stored and run by hardware."
}