travel = {
    "What is the best city in the world ?" : "Your hometown/Your birthplace",
    "How many states are there in India ?" : "29",
    "Which is called the Pink City ?" : "Jaipur",
    "Where is Universal Studios ?" : "Singapore, Florida, Japan, California",
    "How to reach Andaman and Nicobar Islands ?" : "By ship, By flight",
    "Which is the largest country ?" : "Russia",
    "How many modern wonders are there ?" : "Seven",
    "Which City in India is Called The 'Temple City of India' ?" : "Bhubaneswar, Madurai",
    "Which place is called God's own country ?" : "Kerala",
    "Where is Vikram Sarabhai Space Centre ?" : "Thiruvananthapuram",
    "Where is famous Rock garden located ?" : "Chandigarh",
    "Where is Sun temple situated ?" : "Konark",
    "Where is Kaziranga national park located ?" : "Assam",
    "Which is the smallest country in the world ?" : "Vatican city",
    "Which city is called as the Electronic city of India ?" : "Bangalore",
    "Which is the largest Indian state by area ?" : "Rajasthan",
    "Where is Leaning tower of Pisa situated ?" : "Italy",
    "Where is Golden temple situated ?" : "Amristar",
    "Where is famous Khajuraho sculptures located ?" : "Madhya Pradesh",
    "Which is known as 'Garden City of India' ?" : "Bangalore",
    "On which bank of river Badrinath is situated ?" : "Alaknanda",
    "Where is the famous Golconda fort ?" : "Hyderabad, Telengana",
    "In which state Mother Teresa served for poor people ?" : "West bengal",
    "Where is Sanchi Stupa located ?" : "Patna",
    "Where is National Science Centre" : "Delhi",
    "Where is Sahara Desert situated ?" : "Africa",
    "Which place is said to be the cathedral city of india ?" : "Bhubaneshwar",
    "Which city is known as 'City of Blood' in India " : "Tezpur",
    "Which is the smallest cricket stadium in the world by boundary ?" : "Feroz Shah Kotla",
    "Which country has no cinema theaters ?" : "Saudi Arabia",
    "Which is Asia's largest tulip garden" : " Indira Gandhi Memorial Tulip garden",
    "Which is International Rice Research Institute  located in" : "Phillipines",
    "Which city is known as 'Queen of Arabian Sea' ?" : "Kochi",
    "Which is called as a landlock harbour" : "Vishakapatnam",
    "Which valley is known as 'Paradise of Earth' ?" : "Kashmir Valley",
    "Where is Petronas Twin Towers located ?" : "Malaysia",
    "In which country Forbidden city is located ?" : "China",
    "Where is the famous Eiffel Tower" : "Paris",
    "Which country is known as land of kangaroo  ?" : "Australia",
    "Where is Doodh Sagar waterfalls located  ?" : "Goa",
    "Which country is called the Sugar bowl of the world  ?" : "Brazil",
    "Which state has won the 'Best Tourism State' national award ?" : "Madhya Pradesh",
    "Which is the most populous city in the world  ?" : "Tokyo",
    "Which city is known as 'City of Wars' ?" : "Panipat",
    "Which city ranks 40 among top 50 global cities for women entrepreneurs listing ?" : "Bangalore",
    "Which monument is known as 'The National Monument of India' ?" : "India Gate",
    "Which city emerged as the Most Dynamic City in the world" : "Bangalore",
    "Which city is known as the City of Prime Ministers ?" : "Allahabad",
    "Which place is said to be the Manchester of South India ?" : "Coimbatore",
    "Where is the Indian National Rail Museum situated ?" : "Delhi",
    "no.of states in India?" : "29"
}